## This workflow will install Python dependencies, run tests and lint with a single version of Python
## For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
#
#name: fiber develop testnet test
#
#on:
#  workflow_dispatch:
#
#
#permissions:
#  contents: read
#
#jobs:
#  build:
#
#    runs-on: ubuntu-22.04
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up Python 3.10
#      uses: actions/setup-python@v3
#      with:
#        python-version: "3.10"
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#
#    - name: Install dependencies
#      run: make prepare_fiber_testnet
#
#    - name: Run tests
#      run: make fiber_testnet_test
#
##    - name: Setup upterm session
##      if: always()
##      uses: lhotari/action-upterm@v1
#
#    - name: Publish reports
#      if: failure()
#      uses: actions/upload-artifact@v4
#      with:
#        name: jfoa-build-reports-${{ runner.os }}
#        path: ./report
